=== YoussefNSI/L3MI/Dev Web/l3-info-dw-cc+ct_T_T_annexes/cc-17-php-2/annexes/music.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT music (disque+) >
<!ELEMENT disque (titre, musiciens) >
<!ELEMENT titre (#PCDATA) >
<!ELEMENT musiciens (musicien+) >
<!ELEMENT musicien EMPTY >
<!ATTLIST disque annee CDATA #REQUIRED >
<!ATTLIST disque rang CDATA #REQUIRED >
<!ATTLIST musicien nom CDATA #REQUIRED >
<!ATTLIST musicien adn CDATA #REQUIRED >

=== YoussefNSI/L3MI/Dev Web/l3-info-dw-cc+ct_T_T_annexes/cc-17-php-2/annexes/music.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE music SYSTEM "music.dtd">
<music>
<disque annee="1980" rang="157">
<titre>Closer</titre>
<musiciens>
<musicien nom="Curtis" adn="1956"/>
<musicien nom="Summer" adn="1956"/>
</musiciens>
</disque>

<disque annee="1979" rang="8">
<titre>London Calling</titre>
<musiciens>
<musicien nom="Jones" adn="1955"/>
<musicien nom="Strummer" adn="1952"/>
</musiciens>
</disque>

<disque annee="1971" rang="107">
<titre>Hunky Dory</titre>
<musiciens>
<musicien nom="Bowie" adn="1947"/>
</musiciens>
</disque>

<disque annee="1966" rang="2">
<titre>Revolver</titre>
<musiciens>
<musicien nom="Lennon" adn="1940"/>
<musicien nom="McCartney" adn="1942"/>
</musiciens>
</disque>
</music>
