=== YoussefNSI/L3MI/Dev Web/l3-info-dw-cc+ct_T_T_annexes/ct-18-1/annexes/exercice-2/bmi.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT BigMacIndex (country+) >
<!ELEMENT country (name, localPrice, exchangeRates) >
<!ELEMENT name (#PCDATA) >
<!ELEMENT localPrice (#PCDATA) >
<!ELEMENT exchangeRates (dollarOfficial, dollarBMI) >
<!ELEMENT dollarOfficial (#PCDATA) >
<!ELEMENT dollarBMI (#PCDATA) >
<!ATTLIST country code CDATA #REQUIRED>

=== YoussefNSI/L3MI/Dev Web/l3-info-dw-cc+ct_T_T_annexes/ct-18-1/annexes/exercice-2/bmi.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE BigMacIndex SYSTEM "bmi.dtd">
<BigMacIndex>
	<country code="AR">
		<name>Argentina</name>
		<localPrice>21</localPrice>
		<exchangeRates>
			<dollarOfficial>8.17</dollarOfficial>
			<dollarBMI>4.38</dollarBMI>
		</exchangeRates>
		</country>
		<country code="AU">
			<name>Australia</name>
			<localPrice>5.1</localPrice>
			<exchangeRates>
				<dollarOfficial>1.06</dollarOfficial>
				<dollarBMI>1.06</dollarBMI>
			</exchangeRates>
		</country>
		<country code="BR">
			<name>Brazil</name>
			<localPrice>13</localPrice>
			<exchangeRates>
				<dollarOfficial>2.22</dollarOfficial>
				<dollarBMI>2.71</dollarBMI>
			</exchangeRates>
		</country>
		<country code="GB">
			<name>Britain</name>
			<localPrice>2.89</localPrice>
			<exchangeRates>
				<dollarOfficial>0.59</dollarOfficial>
				<dollarBMI>0.60</dollarBMI>
			</exchangeRates>
		</country>
		<country code="CA">
			<name>Canada</name>
			<localPrice>5.64</localPrice>
			<exchangeRates>
				<dollarOfficial>1.07</dollarOfficial>
				<dollarBMI>1.18</dollarBMI>
			</exchangeRates>
		</country>
		<country code="CN">
			<name>China</name>
			<localPrice>16.9</localPrice>
			<exchangeRates>
				<dollarOfficial>6.20</dollarOfficial>
				<dollarBMI>3.52</dollarBMI>
			</exchangeRates>
		</country>
		<country code="EG">
			<name>Egypt</name>
			<localPrice>16.93</localPrice>
			<exchangeRates>
				<dollarOfficial>7.15</dollarOfficial>
				<dollarBMI>3.53</dollarBMI>
			</exchangeRates>
		</country>
		<country code="FR">
			<name>France</name>
			<localPrice>3.9</localPrice>
			<exchangeRates>
				<dollarOfficial>0.74</dollarOfficial>
				<dollarBMI>0.81</dollarBMI>
			</exchangeRates>
		</country>
		<country code="DE">
			<name>Germany</name>
			<localPrice>3.67</localPrice>
			<exchangeRates>
				<dollarOfficial>0.74</dollarOfficial>
				<dollarBMI>0.77</dollarBMI>
			</exchangeRates>
		</country>
		<country code="IN">
			<name>India</name>
			<localPrice>105</localPrice>
			<exchangeRates>
				<dollarOfficial>60.09</dollarOfficial>
				<dollarBMI>21.90</dollarBMI>
			</exchangeRates>
		</country>
		<country code="ID">
			<name>Indonesia</name>
			<localPrice>27939</localPrice>
			<exchangeRates>
				<dollarOfficial>11505.00</dollarOfficial>
				<dollarBMI>5826.69</dollarBMI>
			</exchangeRates>
		</country>
		<country code="IL">
			<name>Israel</name>
			<localPrice>17.5</localPrice>
			<exchangeRates>
				<dollarOfficial>3.41</dollarOfficial>
				<dollarBMI>3.65</dollarBMI>
			</exchangeRates>
		</country>
		<country code="JP">
			<name>Japan</name>
			<localPrice>370</localPrice>
			<exchangeRates>
				<dollarOfficial>101.53</dollarOfficial>
				<dollarBMI>77.16</dollarBMI>
			</exchangeRates>
		</country>
		<country code="MX">
			<name>Mexico</name>
			<localPrice>42</localPrice>
			<exchangeRates>
				<dollarOfficial>12.93</dollarOfficial>
				<dollarBMI>8.76</dollarBMI>
			</exchangeRates>
		</country>
		<country code="NZ">
			<name>New Zealand</name>
			<localPrice>5.7</localPrice>
			<exchangeRates>
				<dollarOfficial>1.15</dollarOfficial>
				<dollarBMI>1.19</dollarBMI>
			</exchangeRates>
		</country>
		<country code="PK">
			<name>Pakistan</name>
			<localPrice>300</localPrice>
			<exchangeRates>
				<dollarOfficial>98.68</dollarOfficial>
				<dollarBMI>62.57</dollarBMI>
			</exchangeRates>
		</country>
		<country code="PH">
			<name>Philippines</name>
			<localPrice>160</localPrice>
			<exchangeRates>
				<dollarOfficial>43.21</dollarOfficial>
				<dollarBMI>33.37</dollarBMI>
			</exchangeRates>
		</country>
		<country code="RU">
			<name>Russia</name>
			<localPrice>89</localPrice>
			<exchangeRates>
				<dollarOfficial>34.84</dollarOfficial>
				<dollarBMI>18.56</dollarBMI>
			</exchangeRates>
		</country>
		<country code="SA">
			<name>Saudi Arabia</name>
			<localPrice>11</localPrice>
			<exchangeRates>
				<dollarOfficial>3.75</dollarOfficial>
				<dollarBMI>2.29</dollarBMI>
			</exchangeRates>
		</country>
		<country code="SG">
			<name>Singapore</name>
			<localPrice>4.7</localPrice>
			<exchangeRates>
				<dollarOfficial>1.24</dollarOfficial>
				<dollarBMI>0.98</dollarBMI>
			</exchangeRates>
		</country>
		<country code="ZA">
			<name>South Africa</name>
			<localPrice>24.5</localPrice>
			<exchangeRates>
				<dollarOfficial>10.51</dollarOfficial>
				<dollarBMI>5.11</dollarBMI>
			</exchangeRates>
		</country>
		<country code="AE">
			<name>UAE</name>
			<localPrice>13</localPrice>
			<exchangeRates>
				<dollarOfficial>3.67</dollarOfficial>
				<dollarBMI>2.71</dollarBMI>
			</exchangeRates>
		</country>
		<country code="US">
			<name>United States</name>
			<localPrice>4.795</localPrice>
			<exchangeRates>
				<dollarOfficial>1.00</dollarOfficial>
				<dollarBMI>1.00</dollarBMI>
			</exchangeRates>
		</country>
</BigMacIndex>
