=== YoussefNSI/L3MI/Dev Web/l3-info-dw-cc+ct_T_T_annexes/ct-22-1/annexes/php/src/atomes.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT atomes (atome+) >
<!ELEMENT atome (nom, numero, symbole, masse_atomique, annee_decouverte, pays_decouverte, radioactif, groupe, periode) >
<!ELEMENT nom (#PCDATA) >
<!ELEMENT numero (#PCDATA) >
<!ELEMENT symbole (#PCDATA) >
<!ELEMENT masse_atomique (#PCDATA) >
<!ELEMENT annee_decouverte (#PCDATA) >
<!ELEMENT pays_decouverte (pays*) >
<!ELEMENT pays (nom_pays)> 
<!ELEMENT nom_pays (#PCDATA) >
<!ELEMENT radioactif (#PCDATA) >
<!ELEMENT groupe (#PCDATA) >
<!ELEMENT periode (#PCDATA) >

=== YoussefNSI/L3MI/Dev Web/l3-info-dw-cc+ct_T_T_annexes/ct-22-1/annexes/php/src/atomes-exemple.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE atomes SYSTEM 'atomes.dtd'>
<atomes>
    <atome>
        <nom>Hydrogène</nom>
        <numero>1</numero>
        <symbole>H</symbole>
        <masse_atomique>1.00794</masse_atomique>
        <annee_decouverte>1766</annee_decouverte>
        <pays_decouverte>
            <pays>
                <nom_pays>Grande-Bretagne</nom_pays>
            </pays>
        </pays_decouverte>
        <radioactif>false</radioactif>
        <groupe>1</groupe>
        <periode>1</periode>
    </atome>
    <atome>
        <nom>Hélium</nom>
        <numero>2</numero>
        <symbole>He</symbole>
        <masse_atomique>4.002602</masse_atomique>
        <annee_decouverte>1895</annee_decouverte>
        <pays_decouverte>
            <pays>
                <nom_pays>Grande-Bretagne</nom_pays>
            </pays>
        </pays_decouverte>
        <radioactif>false</radioactif>
        <groupe>18</groupe>
        <periode>1</periode>
    </atome>
    <atome>
        <nom>Lithium</nom>
        <numero>3</numero>
        <symbole>Li</symbole>
        <masse_atomique>6.941</masse_atomique>
        <annee_decouverte>1817</annee_decouverte>
        <pays_decouverte>
            <pays>
                <nom_pays>Suède</nom_pays>
            </pays>
        </pays_decouverte>
        <radioactif>false</radioactif>
        <groupe>1</groupe>
        <periode>2</periode>
    </atome>
    <atome>
        <nom>Béryllium</nom>
        <numero>4</numero>
        <symbole>Be</symbole>
        <masse_atomique>9.012182</masse_atomique>
        <annee_decouverte>1798</annee_decouverte>
        <pays_decouverte>
            <pays>
                <nom_pays>France</nom_pays>
            </pays>
        </pays_decouverte>
        <radioactif>false</radioactif>
        <groupe>2</groupe>
        <periode>2</periode>
    </atome>
    <atome>
        <nom>Bore</nom>
        <numero>5</numero>
        <symbole>B</symbole>
        <masse_atomique>10.811</masse_atomique>
        <annee_decouverte>1808</annee_decouverte>
        <pays_decouverte>
            <pays>
                <nom_pays>France</nom_pays>
            </pays>
            <pays>
                <nom_pays>Grande-Bretagne</nom_pays>
            </pays>
        </pays_decouverte>
        <radioactif>false</radioactif>
        <groupe>13</groupe>
        <periode>2</periode>
    </atome>
    <atome>
        <nom>Carbone</nom>
        <numero>6</numero>
        <symbole>C</symbole>
        <masse_atomique>12.0107</masse_atomique>
        <annee_decouverte>0</annee_decouverte>
        <pays_decouverte />
        <radioactif>false</radioactif>
        <groupe>14</groupe>
        <periode>2</periode>
    </atome>
    <atome>
        <nom>Azote</nom>
        <numero>7</numero>
        <symbole>N</symbole>
        <masse_atomique>14.0067</masse_atomique>
        <annee_decouverte>1772</annee_decouverte>
        <pays_decouverte>
            <pays>
                <nom_pays>Écosse</nom_pays>
            </pays>
        </pays_decouverte>
        <radioactif>false</radioactif>
        <groupe>15</groupe>
        <periode>2</periode>
    </atome>
    <atome>
        <nom>Oxygène</nom>
        <numero>8</numero>
        <symbole>O</symbole>
        <masse_atomique>15.9994</masse_atomique>
        <annee_decouverte>1774</annee_decouverte>
        <pays_decouverte>
            <pays>
                <nom_pays>Grande-Bretagne</nom_pays>
            </pays>
            <pays>
                <nom_pays>Suède</nom_pays>
            </pays>
        </pays_decouverte>
        <radioactif>false</radioactif>
        <groupe>16</groupe>
        <periode>2</periode>
    </atome>
    <atome>
        <nom>Fluor</nom>
        <numero>9</numero>
        <symbole>F</symbole>
        <masse_atomique>18.9984032</masse_atomique>
        <annee_decouverte>1886</annee_decouverte>
        <pays_decouverte>
            <pays>
                <nom_pays>France</nom_pays>
            </pays>
        </pays_decouverte>
        <radioactif>false</radioactif>
        <groupe>17</groupe>
        <periode>2</periode>
    </atome>
    <atome>
        <nom>Néon</nom>
        <numero>10</numero>
        <symbole>Ne</symbole>
        <masse_atomique>20.1797</masse_atomique>
        <annee_decouverte>1898</annee_decouverte>
        <pays_decouverte>
            <pays>
                <nom_pays>Grande-Bretagne</nom_pays>
            </pays>
        </pays_decouverte>
        <radioactif>false</radioactif>
        <groupe>18</groupe>
        <periode>2</periode>
    </atome>
    <atome>
        <nom>Sodium</nom>
        <numero>11</numero>
        <symbole>Na</symbole>
        <masse_atomique>22.98976928</masse_atomique>
        <annee_decouverte>1807</annee_decouverte>
        <pays_decouverte>
            <pays>
                <nom_pays>Grande-Bretagne</nom_pays>
            </pays>
        </pays_decouverte>
        <radioactif>false</radioactif>
        <groupe>1</groupe>
        <periode>3</periode>
    </atome>
    <atome>
        <nom>Magnésium</nom>
        <numero>12</numero>
        <symbole>Mg</symbole>
        <masse_atomique>24.305</masse_atomique>
        <annee_decouverte>1775</annee_decouverte>
        <pays_decouverte>
            <pays>
                <nom_pays>Écosse</nom_pays>
            </pays>
        </pays_decouverte>
        <radioactif>false</radioactif>
        <groupe>2</groupe>
        <periode>3</periode>
    </atome>
    <atome>
        <nom>Aluminium</nom>
        <numero>13</numero>
        <symbole>Al</symbole>
        <masse_atomique>26.9815386</masse_atomique>
        <annee_decouverte>1827</annee_decouverte>
        <pays_decouverte>
            <pays>
                <nom_pays>Danemark</nom_pays>
            </pays>
        </pays_decouverte>
        <radioactif>false</radioactif>
        <groupe>13</groupe>
        <periode>3</periode>
    </atome>
    <atome>
        <nom>Silicium</nom>
        <numero>14</numero>
        <symbole>Si</symbole>
        <masse_atomique>28.0855</masse_atomique>
        <annee_decouverte>1824</annee_decouverte>
        <pays_decouverte>
            <pays>
                <nom_pays>Suède</nom_pays>
            </pays>
        </pays_decouverte>
        <radioactif>false</radioactif>
        <groupe>14</groupe>
        <periode>3</periode>
    </atome>
    <atome>
        <nom>Phosphore</nom>
        <numero>15</numero>
        <symbole>P</symbole>
        <masse_atomique>30.973762</masse_atomique>
        <annee_decouverte>1669</annee_decouverte>
        <pays_decouverte>
            <pays>
                <nom_pays>Allemagne</nom_pays>
            </pays>
        </pays_decouverte>
        <radioactif>false</radioactif>
        <groupe>15</groupe>
        <periode>3</periode>
    </atome>
    <atome>
        <nom>Soufre</nom>
        <numero>16</numero>
        <symbole>S</symbole>
        <masse_atomique>32.065</masse_atomique>
        <annee_decouverte>0</annee_decouverte>
        <pays_decouverte />
        <radioactif>false</radioactif>
        <groupe>16</groupe>
        <periode>3</periode>
    </atome>
    <atome>
        <nom>Chlore</nom>
        <numero>17</numero>
        <symbole>Cl</symbole>
        <masse_atomique>35.453</masse_atomique>
        <annee_decouverte>1774</annee_decouverte>
        <pays_decouverte>
            <pays>
                <nom_pays>Suède</nom_pays>
            </pays>
        </pays_decouverte>
        <radioactif>false</radioactif>
        <groupe>17</groupe>
        <periode>3</periode>
    </atome>
    <atome>
        <nom>Argon</nom>
        <numero>18</numero>
        <symbole>Ar</symbole>
        <masse_atomique>39.948</masse_atomique>
        <annee_decouverte>1894</annee_decouverte>
        <pays_decouverte />
        <radioactif>false</radioactif>
        <groupe>18</groupe>
        <periode>3</periode>
    </atome>
    <atome>
        <nom>Potassium</nom>
        <numero>19</numero>
        <symbole>K</symbole>
        <masse_atomique>39.0983</masse_atomique>
        <annee_decouverte>1807</annee_decouverte>
        <pays_decouverte>
            <pays>
                <nom_pays>Grande-Bretagne</nom_pays>
            </pays>
        </pays_decouverte>
        <radioactif>false</radioactif>
        <groupe>1</groupe>
        <periode>4</periode>
    </atome>
    <atome>
        <nom>Calcium</nom>
        <numero>20</numero>
        <symbole>Ca</symbole>
        <masse_atomique>40.078</masse_atomique>
        <annee_decouverte>1808</annee_decouverte>
        <pays_decouverte>
            <pays>
                <nom_pays>Grande-Bretagne</nom_pays>
            </pays>
        </pays_decouverte>
        <radioactif>false</radioactif>
        <groupe>2</groupe>
        <periode>4</periode>
    </atome>
    <atome>
        <nom>Scandium</nom>
        <numero>21</numero>
        <symbole>Sc</symbole>
        <masse_atomique>44.955912</masse_atomique>
        <annee_decouverte>1879</annee_decouverte>
        <pays_decouverte>
            <pays>
                <nom_pays>Suède</nom_pays>
            </pays>
        </pays_decouverte>
        <radioactif>false</radioactif>
        <groupe>3</groupe>
        <periode>4</periode>
    </atome>
    <atome>
        <nom>Titane</nom>
        <numero>22</numero>
        <symbole>Ti</symbole>
        <masse_atomique>47.867</masse_atomique>
        <annee_decouverte>1791</annee_decouverte>
        <pays_decouverte>
            <pays>
                <nom_pays>Grande-Bretagne</nom_pays>
            </pays>
        </pays_decouverte>
        <radioactif>false</radioactif>
        <groupe>4</groupe>
        <periode>4</periode>
    </atome>
    <atome>
        <nom>Vanadium</nom>
        <numero>23</numero>
        <symbole>V</symbole>
        <masse_atomique>50.9415</masse_atomique>
        <annee_decouverte>1901</annee_decouverte>
        <pays_decouverte>
            <pays>
                <nom_pays>Suède</nom_pays>
            </pays>
