=== YoussefNSI/L3MI/Dev Web/cc-23-php-solution/data/map.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT map (graph, labeling)>
<!ELEMENT graph (size, arcs)>
<!ELEMENT size EMPTY>
<!ELEMENT arcs (arc*)>
<!ELEMENT arc EMPTY>
<!ELEMENT labeling (nodes, influence_domain, labels)>
<!ELEMENT nodes (node*)>
<!ELEMENT node (#PCDATA)>
<!ELEMENT influence_domain EMPTY>
<!ELEMENT labels (b_label* | int_label* | r_label* | s_label*)>
<!ELEMENT b_label EMPTY>
<!ELEMENT int_label EMPTY>
<!ELEMENT r_label EMPTY>
<!ELEMENT s_label EMPTY>

<!ATTLIST map name CDATA #REQUIRED>

<!ATTLIST size nodes CDATA #REQUIRED>
<!ATTLIST size arcs CDATA #REQUIRED>

<!ATTLIST arc id CDATA #REQUIRED>
<!ATTLIST arc tail CDATA #REQUIRED>
<!ATTLIST arc head CDATA #REQUIRED>


<!ATTLIST node node CDATA #REQUIRED>

<!ATTLIST influence_domain type (boolean|integer|rational|symbolic) #REQUIRED>

<!ATTLIST b_label arc CDATA #REQUIRED>
<!ATTLIST b_label value CDATA #REQUIRED>

<!ATTLIST int_label arc CDATA #REQUIRED>
<!ATTLIST int_label value CDATA #REQUIRED>

<!ATTLIST r_label arc CDATA #REQUIRED>
<!ATTLIST r_label numerator CDATA #REQUIRED>
<!ATTLIST r_label denominator CDATA #REQUIRED>

<!ATTLIST s_label arc CDATA #REQUIRED>
<!ATTLIST s_label value CDATA #REQUIRED>

=== YoussefNSI/L3MI/Dev Web/cc-23-php-sujet/data/map_driving.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE map SYSTEM 'map.dtd'>
<map name="map_driving">
    <graph>
        <!-- `size` attributes: -->
        <!-- `nodes`: number of nodes (>=0) -->
        <!-- `arcs`: number of arcs (>=0) -->
        <size nodes="8" arcs="8"/>
        <!-- nodes are implicitly identified in the range {1..nodes} -->
        <!-- `arcs` includes one `arc` sub-element per arc -->
        <arcs>
            <!-- `arc` attributes: -->
            <!-- `id`  : arc id (in range 1..size.arcs) -->
            <!-- `tail`: tail node id (in range 1..size.nodes) -->
            <!-- `head`: head node id (in range 1..size.nodes) -->
            <arc id="1" tail="1" head="5"/>
            <arc id="2" tail="2" head="5"/>
            <arc id="3" tail="2" head="6"/>
            <arc id="4" tail="3" head="7"/>
            <arc id="5" tail="4" head="7"/>
            <arc id="6" tail="5" head="8"/>
            <arc id="7" tail="6" head="8"/>
            <arc id="8" tail="7" head="8"/>
        </arcs>
    </graph>

    <labeling>
        <!-- `nodes` includes one `node` sub-element per node -->
        <nodes>
            <!-- `node` required attributes: -->
            <!-- `node`: node num (in range 1..digraph.size.nodes) -->
            <!-- text content: node name -->
            <node node="1">brouillard</node>
            <node node="2">pluie</node>
            <node node="3">autoroute</node>
            <node node="4">route secondaire</node>
            <node node="5">mauvaise visibilitÃ©</node>
            <node node="6">route glisssante</node>
            <node node="7">route sineuse</node>
            <node node="8">accident</node>
        </nodes>
        <!-- `influence_domain` required attributes: -->
        <!-- `type`: value types for labeling arcs (integer or symbolic) -->
        <influence_domain type="integer"/>
        <!-- `arc`: the id of the labelled arc (in 1..digraph.size.arcs} -->
        <!-- `int_label`     : attribute `value` (integer, possibly signed) -->
        <!-- `symbolic_label`: attribute `value` (string) -->
        <labels>
            <int_label arc="1" value="9" />
            <int_label arc="2" value="5" />
            <int_label arc="3" value="2" />
            <int_label arc="4" value="-9" />
            <int_label arc="5" value="7" />
            <int_label arc="6" value="7" />
            <int_label arc="7" value="8" />
            <int_label arc="8" value="2" />
        </labels>
    </labeling>
</map>
