=== YoussefNSI/L3MI/Dev Web/l3-info-dw-cc+ct_T_T_annexes/ct-15-1/annexes/population.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT regions (region+) >
<!ELEMENT region (nom, liste_villes, densite) >
<!ELEMENT nom (#PCDATA) >
<!ELEMENT liste_villes (ville+) >
<!ELEMENT densite (#PCDATA) >
<!ELEMENT ville EMPTY >
<!ATTLIST ville nom CDATA #REQUIRED >
<!ATTLIST ville population CDATA #REQUIRED >
<!ATTLIST ville prefecture CDATA #IMPLIED >

=== YoussefNSI/L3MI/Dev Web/l3-info-dw-cc+ct_T_T_annexes/ct-15-1/annexes/population.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE regions SYSTEM "population.dtd">
<regions>
<region>
  <nom>Pays de la Loire</nom>
  <liste_villes>
     <ville nom="Saumur" population="27486"/>
     <ville nom="Nantes" population="282047" prefecture="true"/>
  </liste_villes>
  <densite>109</densite>
</region>
<region>
  <nom>Provence-Alpes-CÃ´te d'Azur</nom>
  <liste_villes>
     <ville nom="Avignon" population="89592" prefecture="true"/>
     <ville nom="Marseille" population="850602" prefecture="true"/>
     <ville nom="Toulon" population="165514" prefecture="true"/>
  </liste_villes>
  <densite>155</densite>
</region>
</regions>
